apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argo-cd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: argo-cd
    server: https://kubernetes.default.svc
  - namespace: ingress-nginx
    server: https://kubernetes.default.svc
  - namespace: velero
    server: https://kubernetes.default.svc
  - namespace: podinfo
    server: https://kubernetes.default.svc
  - namespace: semaphore
    server: https://kubernetes.default.svc
  - namespace: localstack
    server: https://kubernetes.default.svc
  - namespace: atlantis
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - 'git@github.com:mecsys/mecsys-gitops.git'
  - 'https://argoproj.github.io/argo-helm'
  - 'https://kubernetes.github.io/ingress-nginx'
  - 'https://vmware-tanzu.github.io/helm-charts'
  - 'https://stefanprodan.github.io/podinfo'
  - 'https://cloudhippie.github.io/charts'
  - 'https://localstack.github.io/helm-charts'
  - 'https://runatlantis.github.io/helm-charts'
  - 'https://schwarzit.github.io/node-red-chart'
