apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: keycloak
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - 'git@github.com:mecsys/mecsys-stacks.git'
  - 'https://charts.bitnami.com/bitnami'
