image:
  keda:
    repository: ghcr.io/kedacore/keda
    tag: "2.13.0"
  metricsApiServer:
    repository: ghcr.io/kedacore/keda-metrics-apiserver
    tag: "2.13.0"
  pullPolicy: Always
  webhooks:
    repository: ghcr.io/kedacore/keda-admission-webhooks
    tag: "2.13.0"

# -- Defines Kubernetes namespaces to watch to scale their workloads. Default watches all namespaces
watchNamespace: ""

crds:
  install: true

# -- Capability to turn on/off ASCII art in Helm installation notes
asciiArt: true

imagePullSecrets: []

# -- [Affinity] for pod scheduling for both KEDA operator and Metrics API Server
affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #       - key: app
  #         operator: In
  #         values:
  #         - keda-operator
  #         - keda-operator-metrics-apiserver
  #     topologyKey: "kubernetes.io/hostname"

operator:
  name: keda-operator
  replicaCount: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - keda-operator
            topologyKey: kubernetes.io/hostname


metricsServer:
  replicaCount: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - keda-operator-metrics-apiserver
            topologyKey: kubernetes.io/hostname

webhooks:  
  enabled: true
  name: keda-admission-webhooks
  replicaCount: 2
  failurePolicy: Ignore
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - keda-admission-webhooks
            topologyKey: kubernetes.io/hostname

podDisruptionBudget:
  metricServer:
    maxUnavailable: 25%
  operator:
    maxUnavailable: 25%
  webhooks:
    maxUnavailable: 25%

resources:
  metricServer:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  operator:
    limits:
      cpu: 1
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 100Mi
  webhooks:
    limits:
      cpu: 50m
      memory: 100Mi
    requests:
      cpu: 10m
      memory: 10Mi

securityContext:
  metricServer:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
  operator:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
  webhooks:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault

logging:
  operator:
    # -- Logging level for KEDA Operator.
    # allowed values: `debug`, `info`, `error`, or an integer value greater than 0, specified as string
    level: error
    # -- Logging format for KEDA Operator.
    # allowed values: `json` or `console`
    format: console
    # -- Logging time encoding for KEDA Operator.
    # allowed values are `epoch`, `millis`, `nano`, `iso8601`, `rfc3339` or `rfc3339nano`
    timeEncoding: rfc3339
  metricServer:
    # -- Logging level for Metrics Server.
    # allowed values: `0` for info, `4` for debug, or an integer value greater than 0, specified as string
    level: 0
    # -- Logging stderrthreshold for Metrics Server
    # allowed values: 'DEBUG','INFO','WARN','ERROR','ALERT','EMERG'
    stderrthreshold: ERROR
  webhooks:
    # -- Logging level for KEDA Operator.
    # allowed values: `debug`, `info`, `error`, or an integer value greater than 0, specified as string
    level: error
    # -- Logging format for KEDA Admission webhooks.
    # allowed values: `json` or `console`
    format: console
    # -- Logging time encoding for KEDA Operator.
    # allowed values are `epoch`, `millis`, `nano`, `iso8601`, `rfc3339` or `rfc3339nano`
    timeEncoding: rfc3339

service:
  # -- KEDA Metric Server service type
  type: ClusterIP
  # -- HTTPS port for KEDA Metric Server service
  portHttps: 443
  # -- HTTPS port for KEDA Metric Server container
  portHttpsTarget: 6443
  # -- Annotations to add the KEDA Metric Server service
  annotations: {}
