apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-keycloak-helm
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack_webhook_openx: '#gitops-new-industries'
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: apps
  sources:
    - chart: keycloak
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 13.3.0
      helm:
        releaseName: keycloak
        valueFiles:          
          - $values/helm/services/mecsys/production/values.yaml
    - ref: values
      repoURL: git@github.com:mecsys/mecsys-stacks.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true