apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-keycloakx-helm
  namespace: argo-cd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack_webhook_openx: '#gitops-new-industries'
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: apps
  sources:
    - chart: keycloakx
      repoURL: https://codecentric.github.io/helm-charts
      targetRevision: 6.0.0
      helm:
        releaseName: keycloak
        valueFiles:          
          - $values/helm/services/mecsys/production/keycloak/keycloak-values.yaml
    - ref: values
      repoURL: git@github.com:mecsys/mecsys-stacks.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true