apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-keycloak-mysql-helm
  namespace: argo-cd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack_webhook_openx: '#gitops-new-industries'
spec:
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  project: apps
  sources:
    - chart: mysql
      repoURL: registry-1.docker.io/bitnamicharts/mysql
      targetRevision: 12.2.1
      helm:
        releaseName: mysql
        valueFiles:          
          - $values/helm/services/mecsys/production/keycloak/mysql-values.yaml
    - ref: values
      repoURL: git@github.com:mecsys/mecsys-stacks.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true