applications:
  argocd-app-of-apps:
    namespace: argo-cd
    project: infra
    source:
      path: apps/production
      repoURL: git@github.com:mecsys/mecsys-gitops.git
      targetRevision: main
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: argo-cd      
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
    - resources-finalizer.argocd.argoproj.io
  argocd-app-of-appprojects:  
    namespace: argo-cd
    project: default     
    source:
      path: projects/production
      repoURL: git@github.com:mecsys/mecsys-gitops.git
      targetRevision: main
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: argo-cd 
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
    - resources-finalizer.argocd.argoproj.io
  argocd-app-of-infras:    
    namespace: argo-cd
    project: infra
    source:
      path: infrastructure/production/apps
      repoURL: git@github.com:mecsys/mecsys-gitops.git
      targetRevision: main
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: argo-cd  
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
    - resources-finalizer.argocd.argoproj.io
