apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluxcd
  namespace: argo-cd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack_webhook_openx: '#gitops-new-industries'
spec:
  destination:
    namespace: flux-system
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: flux2
      repoURL: https://fluxcd-community.github.io/helm-charts
      targetRevision: 2.14.0
      helm:
        releaseName: flux-cd
        valueFiles:
          - $values/infrastructure/production/infra-values/fluxcd/values.yaml          
    - ref: values
      repoURL: git@github.com:mecsys/mecsys-gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
