apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-ingress-nginx-helm
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack_webhook_openx: '#gitops-new-industries'
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.4.2
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/infrastructure/production/infra-values/ingress-nginx/values.yaml        
    - ref: values
      repoURL: git@github.com:mecsys/mecsys-gitops.git
      targetRevision: main
  syncPolicy:
    automated: {}