apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-metrics-server
  namespace: argo-cd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook_openx: '#gitops-new-industries'
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack_webhook_openx: '#gitops-new-industries'
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  sources:
    - chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server
      targetRevision: 3.12.2
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/infrastructure/production/infra-values/metrics-server/values.yaml
    - ref: values
      repoURL: git@github.com:mecsys/mecsys-gitops.git
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
