affinity: {}
backend: null
backends: []
cache: ""
certificate:
  create: false
  dnsNames:
  - podinfo
  issuerRef:
    kind: ClusterIssuer
    name: self-signed
faults:
  delay: false
  error: false
  testFail: false
  testTimeout: false
  unhealthy: false
  unready: false
h2c:
  enabled: false
host: null
hpa:
  cpu: null
  enabled: false
  maxReplicas: 10
  memory: null
  requests: null
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.5.1
image.repository: ghcr.io/stefanprodan/podinfo
image.tag: 6.6.3
ingress:
  additionalLabels: {}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  className: nginx
  enabled: true
  hosts:
  - host: brick.mecsys.com.br
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - hosts:
    - brick.mecsys.com.br
    secretName: brick-mecsys-com-br-cert
linkerd:
  profile:
    enabled: false
logLevel: info
nodeSelector: {}
podAnnotations: {}
probes:
  liveness:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readiness:
    failureThreshold: 3
    initialDelaySeconds: 1
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  startup:
    enable: false
    failureThreshold: 20
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
redis:
  enabled: false
  repository: redis
  tag: 7.0.7
replicaCount: 1
resources:
  limits: null
  requests:
    cpu: 1m
    memory: 16Mi
securityContext: {}
service:
  annotations: {}
  enabled: true
  externalPort: 9898
  grpcPort: 9999
  grpcService: podinfo
  hostPort: null
  httpPort: 9898
  metricsPort: 9797
  nodePort: 31198
  type: ClusterIP
serviceAccount:
  enabled: false
  imagePullSecrets: []
  name: null
serviceMonitor:
  additionalLabels: {}
  enabled: false
  interval: 15s
tls:
  certPath: /data/cert
  enabled: false
  hostPort: null
  port: 9899
  secretName: null
tolerations: []
ui:
  color: '#34577c'
  logo: ""
  message: ""
