replicaCount: 1
logLevel: info
host: null
backend: null
backends: []
image:
  repository: ghcr.io/stefanprodan/podinfo
  tag: 6.7.1
  pullPolicy: IfNotPresent
ui:
  color: '#34577c'
  message: ""
  logo: ""
faults:
  delay: false
  error: false
  unhealthy: false
  unready: false
  testFail: false
  testTimeout: false
service:
  enabled: true
  annotations: {}
  type: ClusterIP
  metricsPort: 9797
  httpPort: 9898
  externalPort: 9898
  grpcPort: 9999
  grpcService: podinfo
  nodePort: 31198
  hostPort: null
h2c:
  enabled: false
tls:
  enabled: false
  secretName: null
  certPath: /data/cert
  port: 9899
  hostPort: null
certificate:
  create: false
  issuerRef:
    kind: ClusterIssuer
    name: self-signed
  dnsNames:
  - podinfo
hpa:
  enabled: false
  maxReplicas: 10
  cpu: null
  memory: null
  requests: null
cache: ""
redis:
  enabled: false
  repository: redis
  tag: 7.0.7
serviceAccount:
  enabled: false
  name: null
  imagePullSecrets: []
securityContext: {}
ingress:
  enabled: true
  className: nginx
  additionalLabels: {}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
  - host: brick.mecsys.com.br
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: brick-mecsys-com-br-cert
    hosts:
    - brick.mecsys.com.br
linkerd:
  profile:
    enabled: false
serviceMonitor:
  enabled: false
  interval: 15s
  additionalLabels: {}
resources:
  limits: null
  requests:
    cpu: 1m
    memory: 16Mi
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
probes:
  readiness:
    initialDelaySeconds: 1
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 1
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
    periodSeconds: 10
  startup:
    enable: false
    initialDelaySeconds: 10
    timeoutSeconds: 5
    failureThreshold: 20
    successThreshold: 1
    periodSeconds: 10
